# @package _global_

distribution_key: X_dim=${distribution.dim_x}__Y_dim=${distribution.dim_y}
alphabet_size: 2
seq_length: 2
x_indices: [0]
y_indices: [1]

distribution:
  _target_: distribution_generator.distributions.get_rv
  # To use shared dimensionality.
  dim_x: 2
  dim_y: 2
  min_val: 0.001