n_runs: 1
seed: 42
to_be_seeded:
  - basic
  - numpy
  - torch

default_grid:
  dimensionality: range(1, 4)

hydra:
  mode: MULTIRUN
  sweep:
    dir: outputs/${now:%Y-%m-%d}
    subdir: ${estimator._target_}/${distribution._target_}/${distribution_key}/N=${n_samples}/n_runs=${n_runs}/${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}
  sweeper:
    max_batch_size: 100 # Makes startup faster, see https://github.com/facebookresearch/hydra/issues/1324.
    params:
      ++n_samples: 10000