# @package _global_

estimator:
  _target_: minde.minde.MINDE
  args:
    log_example_images: False
    return_denoised: False
    model:
      arch: "mlp" # "conv"
      use_ema: True
      preprocessing: "rescale"
      hidden_dim: 32
    training:
      lr: 1e-2
      bs: 256
      accum: 1
      snapshot_freq: 5000
      log_freq: 50
      eval_freq: 5000
      snapshot_freq_for_preemption: 10000
      weight: standard
      snapshot_sampling: True
      ema: 0.999
      checkpoint_dir: "minde_mlp/checkpoints"
      accelerator: "gpu"
      devices: 1
      max_steps: 50001
      val_check_interval: 5000
      p_marginal: 0.5
    inference:
      type: "c"
      mc_iter: 10
      importance_sampling: False
      sigma: 1.0
      bs: 512
      generate_samples: False
